21.09.2025 23:35:46 | ERROR | Ошибка при поиске записи по фильтрам {'telegram_id': 804050819}: Could not determine join condition between parent/child tables on relationship ExersiceEntity.exersice - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
21.09.2025 23:35:46 | ERROR | Ошибка при upsert: Could not determine join condition between parent/child tables on relationship ExersiceEntity.exersice - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
21.09.2025 23:35:46 | ERROR | Ошибка при поиске записи по фильтрам {'telegram_id': 804050819}: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[ExersiceEntity(exersice_entities)]'. Original exception was: Could not determine join condition between parent/child tables on relationship ExersiceEntity.exersice - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
21.09.2025 23:35:46 | ERROR | Ошибка при upsert: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[ExersiceEntity(exersice_entities)]'. Original exception was: Could not determine join condition between parent/child tables on relationship ExersiceEntity.exersice - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
21.09.2025 23:35:48 | ERROR | Ошибка при поиске записи по фильтрам {'telegram_id': 804050819}: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[ExersiceEntity(exersice_entities)]'. Original exception was: Could not determine join condition between parent/child tables on relationship ExersiceEntity.exersice - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
21.09.2025 23:35:48 | ERROR | Ошибка при upsert: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[ExersiceEntity(exersice_entities)]'. Original exception was: Could not determine join condition between parent/child tables on relationship ExersiceEntity.exersice - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
21.09.2025 23:35:52 | ERROR | Ошибка при поиске записи по фильтрам {'telegram_id': 804050819}: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[ExersiceEntity(exersice_entities)]'. Original exception was: Could not determine join condition between parent/child tables on relationship ExersiceEntity.exersice - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
21.09.2025 23:35:52 | ERROR | Ошибка при upsert: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[ExersiceEntity(exersice_entities)]'. Original exception was: Could not determine join condition between parent/child tables on relationship ExersiceEntity.exersice - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
22.09.2025 00:52:26 | ERROR | Ошибка при добавлении записи: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: <app.db.models.models.Diary object at 0x... ('Diary' object cannot be interpreted as an integer)
[SQL: INSERT INTO days (diary_id, user_id, date) VALUES ($1::INTEGER, $2::INTEGER, $3::DATE) RETURNING days.id]
[parameters: (<app.db.models.models.Diary object at 0x116e9cb50>, 4, None)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
22.09.2025 00:53:04 | ERROR | Ошибка при добавлении записи: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.NotNullViolationError'>: null value in column "date" of relation "days" violates not-null constraint
DETAIL:  Failing row contains (1, 5, 5, null).
[SQL: INSERT INTO days (diary_id, user_id, date) VALUES ($1::INTEGER, $2::INTEGER, $3::DATE) RETURNING days.id]
[parameters: (5, 5, None)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
22.09.2025 01:28:29 | ERROR | Ошибка при добавлении записи: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "products_title_key"
DETAIL:  Key (title)=(Гречка) already exists.
[SQL: INSERT INTO products (title, carbs_100g, proteins_100g, fats_100g, kcal_100g) VALUES ($1::VARCHAR, $2::NUMERIC(6, 2), $3::NUMERIC(6, 2), $4::NUMERIC(6, 2), $5::INTEGER) RETURNING products.id]
[parameters: ('Гречка', 10.0, 10.0, 10.0, 100)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
28.09.2025 18:59:40 | ERROR | BaseDAO.add() missing 1 required positional argument: 'session'
28.09.2025 19:02:01 | ERROR | 'bool' object has no attribute 'grams'
